name: notes
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_analytics: ^10.4.4
  google_fonts: ^5.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.3
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

